first_run: true

autostart:
  - name: discord
    sleep: 3

links:
  rinnos: git@gitlab.com:rinnos/rinnos.git 
  dotfiles: git@gitlab.com:rinnos/dotfiles.git
  wallpapers: git@gitlab.com/rinnos/wallpapers.git

paths:
  localdotdir: /mnt/Vault/Dotfiles/Linux/Arch

drives:
  - Vault
  - BigDrive
  - Data

files:
  - ./packages.yaml
  - ./dotfiles.yaml
